### ISSUE TITLE
linux/osx

### ISSUE THREAD

**Issue by Jonathancollinet** [Wiskyt/JS-Project-Creator#1]
Salut,

Dans le script, certaines commandes utilisées sont plutôt orienté OSX, comme "open" par exemple.

Pour open tu peut regarder du côté de 'xdg-open' par exemple.

Je pense qu'il serai bien d'avoir une détection du système pour proposer les choix et les exécutions adéquates.

**Comment by Wiskyt** [comment]
Le script prends maintenant en compte l'OS de l'utilisateur pour effectuer les actions
Merci pour la remarque

**Comment by Jonathancollinet** [comment]
Ok maintenant ça fonctionne :)

https://help.github.com/articles/closing-issues-via-commit-messages/
